### ISSUE TITLE
Udaranje crne kugle dok se krece

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG89-bilijar-karambol#2]
Trenutno je dozvoljeno ponovo udariti crnu kuglu dok se krece. Ovo treba onemoguciti, i dopustiti da igracu da udari crnu kuglu samo ako ista stoji u mestu.

**Comment by Emilija100sic** [comment]
Ovaj bug je ispravljen. Sada nije moguce udariti crnu kuglu dok se krece.
